run:
  concurrency: 8
  timeout: 10m
  tests: true
  build-tags: []

output:
  formats:
    text:
      print-issued-lines: true
      print-linter-name: true

linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - goimports
    - gosec
    - govet
    - ineffassign
    - revive
    - typecheck
    - unused

settings:
  govet:
    disable-all: true
    enable:
      - shadow
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurences: 2



