# More info on config here: https://golangci-lint.run/usage/configuration/#config-file

run:
  concurrency: 8
  timeout: 10m
  tests: true
  build-tags: []

output:
  formats: 
    - colored-line-number
  print-issued-lines: true
  print-linter-name: true

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
    - path: \.pb\.go$
    - path: \.pb\.gw\.go$
  exclude:
    - G104 # _ instead of err checks
    - "exported func .* returns unexported type .*, which can be annoying to use"
    - "should have a package comment"
    - "don't use an underscore in package name"

linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - goimports
    - gosec
    - govet
    - ineffassign
    - revive
    - typecheck
    - unused

linters-settings:
  govet:
    enable:
      - shadow
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  revive:
    rules:
      - name: package-comments
        disabled: true
      - name: exported
        arguments:
          - checkTypeParameters
        disabled: false
